config/routes.rb
Rails.application.routes.draw do
  resources :carts, only: [:index, :show, :edit, :update]

  root to: "carts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items

  has_many :products, through: :line_items

  has_many(
    :ordered_products,
    -> { order("line_items.id") },
    through: :line_items,
    source: :product
  )

  def to_param
    marker
  end

  delegate :summary, to: :products, prefix: true
  delegate :last, to: :ordered_products, prefix: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  has_many :carts, through: :line_items

  scope :summary, SummaryScope
end

app/models/product/summary_scope.rb
class Product::SummaryScope
  def self.call(...) = new(...).call

  def call
    module_parent
      .select(select_query)
      .group(:id)
      .order("MIN(code)")
  end

  delegate :module_parent, to: :class

  private

  def select_query
    <<~SQL.squish
      name,
      code,
      price,
      SUM(price) AS total,
      COUNT(*) AS qty
    SQL
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def action_args
    [
      params,
      request
    ]
  end
end

app/controllers/barcodes_controller.rb
class BarcodesController < ApplicationController
  def index
    action = IndexAction.new(*action_args)

    redirect_to barcode_path(action.cart)
  end

  def show
  end

  def update
    @action = UpdateAction.call(*action_args)

    if @action.valid?
      redirect_to @action.cart
    else
      render "show"
    end
  end
end

app/controllers/barcodes_controller/index_action.rb
class BarcodesController::IndexAction
  def self.call(...)
    new(...).call
  end

  def initialize(params, request)
    self.params = params
    self.request = request
  end

  def call
  end

  def cart
    @_cart ||= Cart.create!(marker: SecureRandom.hex(4))
  end

  private

  attr_accessor :params, :user, :request
end

app/controllers/barcodes_controller/update_action.rb
class BarcodesController::UpdateAction
  def self.call(...)
    new(...).call
  end

  def initialize(params, request)
    self.params = params
    self.request = request
  end

  def call
  end

  def valid?
  end

  def cart
    @_cart ||= Cart.find_by!(marker: params.fetch(:id))
  end

  private

  attr_accessor :params, :user, :request
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    action = IndexAction.new(*action_args)

    redirect_to edit_cart_path(action.cart)
  end

  def edit
    @action = EditAction.new(*action_args)
  end

  def show
    @action = ShowAction.new(*action_args)
  end

  def update
    @action = UpdateAction.call(*action_args)

    if @action.valid?
      redirect_to edit_cart_path(@action.cart)
    else
      render "edit"
    end
  end
end

app/controllers/carts_controller/edit_action.rb
class CartsController::EditAction
  extend Adornable

  def initialize(params, request)
    self.params = params
    self.request = request
  end

  def cart
    @_cart ||= Cart.find_by!(marker: params.fetch(:id))
  end

  delegate :message_klass, :message, to: :product

  private

  attr_accessor :params, :request

  decorate :memoize
  def product
    cart.ordered_products_last.then do |value|
      if value
        Product::Presenter.new(cart.ordered_products_last)
      else
        Product::Empty.new
      end
    end
  end
end

app/controllers/carts_controller/index_action.rb
class CartsController::IndexAction
  def self.call(...)
    new(...).call
  end

  def initialize(params, request)
    self.params = params
    self.request = request
  end

  def call
  end

  def cart
    @_cart ||= Cart.create!(marker: SecureRandom.hex(4))
  end

  private

  attr_accessor :params, :user, :request
end

app/controllers/carts_controller/show_action.rb
class CartsController::ShowAction
  def initialize(params, request)
    self.params = params
    self.request = request
  end

  def message_klass
    "btn-outline-success"
  end

  def message
    format("Total: %<total>s", total:)
  end

  def cart
    @_cart ||= Cart.find_by!(marker: params.fetch(:id))
  end

  def products
    Product::Presenter.wrap do
      cart.products_summary
    end
  end

  private

  attr_accessor :params, :request

  def helper
    @_helper ||= ActionController::Base.helpers
  end

  def total
    helper.number_to_currency(
      cart.products_summary.sum(&:total)
    )
  end
end

app/controllers/carts_controller/update_action.rb
class CartsController::UpdateAction
  extend Adornable

  def self.call(...)
    new(...).tap(&:call)
  end

  def initialize(params, request)
    self.params = params
    self.request = request
  end

  def call = result

  decorate :memoize
  def cart = Cart.find_by!(marker: params.fetch(:id))

  delegate :message, :message_klass, to: :product
  delegate :valid?, to: :result

  private

  attr_accessor :params, :user, :request

  decorate :memoize
  def product
    Product::Null.new
  end

  decorate :memoize
  def result = Cart::Inserter.call(cart, code)

  def code = data.fetch(:code)

  def data = params.require(:cart).permit(:code)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/barcodes/show.html.erb
<main class="content">
  <div class="container-fluid p-0">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">

            <div class="row">
              <div class="col-sm-12 text-right">
                <%= link_to root_path, class: "btn btn-primary" do %>
                  Exit
                <% end %>
              </div>
            </div>

            <hr>

            <div class="row">
              <div class="col-sm-12">
                <%= form_with do |f| %>
                  <div class="mb-3">
                    <%= f.label :keywords, class: "form-label" do %> Enter barcode <% end %>
                    <%= f.text_field :keywords, class: "form-control", placeholder: "Type barcode, ex: 123", autofocus: true %>
                  </div>

                  <div class="mt-3">
                    <button type="submit" class="btn btn-primary">Scan</button>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/carts/edit.html.erb
<main class="content">
  <div class="container p-0">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">

            <div class="row">
              <div class="col-md-4 pb-2">
                <%= link_to cart_path(@action.cart), class: "btn btn-primary" do %>
                  Exit
                <% end %>
              </div>

              <div class="col-md-8 text-right">
                <div class="<%= @action.message_klass %> btn w-100 monospace text-right" >
                  <%= @action.message %>
                </div>
              </div>
            </div>

            <hr>

            <div class="row">
              <div class="col-sm-12">
                <%= form_with model: @action.cart, data: { turbo: false } do |f| %>
                  <div class="mb-3">
                    <%= f.label :code, class: "form-label" do %> Enter barcode <% end %>
                    <%= f.text_field :code, class: "form-control", placeholder: "Type barcode (100-199 are valid codes)", autofocus: true %>
                  </div>

                  <div class="mt-3">
                    <button type="submit" class="btn btn-primary">Scan</button>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/carts/show.html.erb
<main class="content">
  <div class="container p-0">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">

            <div class="row">
              <div class="col-md-4 pb-2">
                <%= link_to carts_path, class: "btn btn-primary" do %>
                  Next Customer
                <% end %>
              </div>

              <div class="col-md-8 text-right">
                <div class="<%= @action.message_klass %> btn w-100 monospace text-right" >
                  <%= @action.message %>
                </div>
              </div>
            </div>

            <hr>

            <% if @action.products.any? %>

            <table id="datatables-responsive" class="table table-striped table-sm" style="width:100%" data-turbo="true">
              <thead>
                <tr>
                  <th>Product</th>
                  <th class="text-right">Code</th>
                  <th class="text-right">Qty</th>
                  <th class="text-right">Price</th>
                  <th class="text-right">Total</th>
                </tr>
              </thead>

              <tbody>
                <% @action.products.each do |product| %>
                  <tr>
                    <td> <%= product.name %> </td>
                    <td class="numeric"> <%= product.code %> </td>
                    <td class="numeric"> <%= product.qty %> </td>
                    <td class="cash"> <%= product.pretty_price %> </td>
                    <td class="cash"> <%= product.pretty_total %> </td>
                  </tr>
                <% end %>
              </tbody>
            </table>

            <% else %>

            <div class="alert alert-danger" role="alert">
              <div class="alert-message">
                <strong>Warning!</strong> No products scanned.
              </div>
            </div>

            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_default_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Knowde</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <%#= render Devel::LivereloadDevelopmentComponent.new(env: Rails.env) %>

  <title>Knowde</title>

	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  <link href="/css/light.css" rel="stylesheet">

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.28.0/feather.min.js"></script>
</head>

<body data-theme="default">
  <div class="wrapper">
    <div class="main">

      <%= yield %>

      <footer class="footer">
        <div class="container-fluid">
          <div class="row text-muted">
            <div class="col-6 text-start">
              <ul class="list-inline">
                <li class="list-inline-item">
                  <a class="text-muted" href="#">Support</a>
                </li>
              </ul>
            </div>
            <div class="col-6 text-end">
              <p class="mb-0">
              &copy; <%= Time.now.year %> - <%= link_to "Knowde", root_path, class: "text-muted" %>
              </p>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
</body>
</html>